package it.polimi.ingsw.client;

import it.polimi.ingsw.serializableObjects.Message;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;


/**
 * This class allows to handle the connection with the server
 */
public class NetworkHandler implements Runnable {


    private boolean keepConnected;
    private Socket server;
    private ObjectOutputStream outputStm;
    private ObjectInputStream inputStm;
    private final List<ServerObserver> observers = new ArrayList<>();
    private boolean myTurn = false;


    public NetworkHandler(Socket server, Client client) {
        this.server = server;
        keepConnected = true;
        addObserver(client);
        myTurn = false;
    }

    public void init() {

        try {
            outputStm = new ObjectOutputStream(server.getOutputStream());
            inputStm = new ObjectInputStream(server.getInputStream());
        } catch (IOException e) {
            System.out.println("server has died");
        } catch (ClassCastException e) {
            System.out.println("protocol violation");
        }

    }


    public void addObserver(ServerObserver observer) {

        observers.add(observer);

    }


    public void removeObserver(ServerObserver observer) {

        observers.remove(observer);

    }


    @Override
    public void run() {

        init();

        while (keepConnected) {

            Object returnedValue;

            //checkMyTurn();

            try {

                returnedValue = handleServerRequest();

                handleClientResponse(returnedValue);

            } catch (IOException e) {
                e.printStackTrace();
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }

        }

        try {
            server.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }


    private void checkMyTurn() {

        Scanner scanner = new Scanner(System.in);

        while (!myTurn) {

            scanner.nextLine();
            System.out.println("Invalid input, not your turn\n");

            try {
                if (handleServerRequest().equals("start"))
                    myTurn= true;
            } catch(IOException | ClassNotFoundException e ) {
                e.printStackTrace();
            }
        }

    }


    /**
     * Allows to manage the requests received.
     *
     * @throws IOException            generated by inputStream
     * @throws ClassNotFoundException generated by inputStream
     */
    private Object handleServerRequest() throws IOException, ClassNotFoundException {

        Message receivedMessage = (Message) inputStm.readObject();

        if (receivedMessage != null && receivedMessage.getMethod().equals("shutdownClient")) {
            keepConnected = false;
            return null;
        }

        if (receivedMessage != null && (receivedMessage.getMethod().equals("startYourTurn") || receivedMessage.getMethod().equals("endTurn")) ) {
            //myTurn = true;
            return observers.get(0).setMyTurn(receivedMessage);
        }

        if (receivedMessage != null) {
            return observers.get(0).update(receivedMessage);
        }


        return null;

    }


    private void handleClientResponse(Object clientResponse) throws IOException {

        if (clientResponse == null)
            return;

        outputStm.writeObject(clientResponse);

    }


}
