package it.polimi.ingsw.client;

import it.polimi.ingsw.serializableObjects.Message;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.SynchronousQueue;


/**
 * This class allows to handle the connection with the server
 */
public class NetworkHandler implements Runnable {


    private volatile boolean connected;
    private final Socket server;
    private ObjectOutputStream outputStm;
    private final Client client;
    private InputReader inputReader;


    public NetworkHandler(Socket server, Client client) {
        this.server = server;
        connected = true;
        this.client = client;



        try {
            outputStm = new ObjectOutputStream(server.getOutputStream());
        } catch (IOException e) {
            System.out.println("server has died");
        } catch (ClassCastException e) {
            System.out.println("protocol violation");
        }

         inputReader = new InputReader(server,client);
         new Thread(inputReader).start();

    }


    public boolean isConnected() {
        return connected;
    }


    @Override
    public void run() {

        while (inputReader.isConnected()) {

            try {

                Object returnedValue = handleServerRequest();

                handleClientResponse(returnedValue);

            } catch (IOException | ClassNotFoundException e) {
                e.printStackTrace();

            }

        }

        disconnect();

    }


    /**
     * Allows to manage the requests received.
     *
     * @throws IOException            generated by inputStream
     * @throws ClassNotFoundException generated by inputStream
     */
    private Object handleServerRequest() throws IOException, ClassNotFoundException {

        Message receivedMessage = null;

        try {

            receivedMessage = (Message) inputReader.getObjectsQueue().take();


        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        if (receivedMessage == null)
            return null;


        return client.update(receivedMessage);
    }


    public synchronized void handleClientResponse(Object clientResponse) throws IOException {

        if (clientResponse == null)
            return;

        outputStm.writeObject(clientResponse);

    }

    public void disconnect(){
        System.out.println("Network handler received disconnected");
        this.connected = false;
    }

    public InputReader getInputReader() {
        return inputReader;
    }


}
